### ISSUE TITLE
[Major] Код 500 Internal Server Error при отправке GET /api/users/me/  без авторизации

### ISSUE THREAD

**Issue by anahomma** [a-platform-for-designers/a-platform-for-designers-backend#45]
**Окружение:** 
Адрес сервера: http://46.183.163.139

**Шаги для воспроизведения:**

Отправить GET /api/users/me/  

**Ожидаемый результат:** 401 Unauthorized  / 403 Forbidden 
**Фактический результат:** 500 Internal Server Error

**Дополнительные материалы:**
curl --location 'http://46.183.163.139/api/users/me/'

**Comment by anahomma** [comment]
04.12. Баг не исправлен

**Comment by Dave-YP** [comment]
Бага больше нет. Страница теперь доступна через  http://46.183.163.139/api/auth/users/me/. Там код 401 выдает.
